"""autogenerated by genpy from explorer_msgs/explorer_low_level_data.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class explorer_low_level_data(genpy.Message):
  _md5sum = "464c3ddb9b7fad8e12a26ddca6b44988"
  _type = "explorer_msgs/explorer_low_level_data"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int64 low_level_id
float64 can_serial_data_1
float64 can_serial_data_2

"""
  __slots__ = ['low_level_id','can_serial_data_1','can_serial_data_2']
  _slot_types = ['int64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       low_level_id,can_serial_data_1,can_serial_data_2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(explorer_low_level_data, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.low_level_id is None:
        self.low_level_id = 0
      if self.can_serial_data_1 is None:
        self.can_serial_data_1 = 0.
      if self.can_serial_data_2 is None:
        self.can_serial_data_2 = 0.
    else:
      self.low_level_id = 0
      self.can_serial_data_1 = 0.
      self.can_serial_data_2 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_q2d.pack(_x.low_level_id, _x.can_serial_data_1, _x.can_serial_data_2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.low_level_id, _x.can_serial_data_1, _x.can_serial_data_2,) = _struct_q2d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_q2d.pack(_x.low_level_id, _x.can_serial_data_1, _x.can_serial_data_2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.low_level_id, _x.can_serial_data_1, _x.can_serial_data_2,) = _struct_q2d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_q2d = struct.Struct("<q2d")
