"""autogenerated by genpy from explorer_msgs/explorer_arm.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class explorer_arm(genpy.Message):
  _md5sum = "4aa934b0f8c59a1bdf03cc34f92ab0cb"
  _type = "explorer_msgs/explorer_arm"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 end_link_move_x
float64 end_link_move_y
float64 camera_pitch
float64 camera_yaw
float64 arm_yaw

"""
  __slots__ = ['end_link_move_x','end_link_move_y','camera_pitch','camera_yaw','arm_yaw']
  _slot_types = ['float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       end_link_move_x,end_link_move_y,camera_pitch,camera_yaw,arm_yaw

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(explorer_arm, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.end_link_move_x is None:
        self.end_link_move_x = 0.
      if self.end_link_move_y is None:
        self.end_link_move_y = 0.
      if self.camera_pitch is None:
        self.camera_pitch = 0.
      if self.camera_yaw is None:
        self.camera_yaw = 0.
      if self.arm_yaw is None:
        self.arm_yaw = 0.
    else:
      self.end_link_move_x = 0.
      self.end_link_move_y = 0.
      self.camera_pitch = 0.
      self.camera_yaw = 0.
      self.arm_yaw = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_5d.pack(_x.end_link_move_x, _x.end_link_move_y, _x.camera_pitch, _x.camera_yaw, _x.arm_yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.end_link_move_x, _x.end_link_move_y, _x.camera_pitch, _x.camera_yaw, _x.arm_yaw,) = _struct_5d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_5d.pack(_x.end_link_move_x, _x.end_link_move_y, _x.camera_pitch, _x.camera_yaw, _x.arm_yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.end_link_move_x, _x.end_link_move_y, _x.camera_pitch, _x.camera_yaw, _x.arm_yaw,) = _struct_5d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_5d = struct.Struct("<5d")
