// Generated by gencpp from file explorer_msgs/explorer_vice_wheel.msg
// DO NOT EDIT!


#ifndef EXPLORER_MSGS_MESSAGE_EXPLORER_VICE_WHEEL_H
#define EXPLORER_MSGS_MESSAGE_EXPLORER_VICE_WHEEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace explorer_msgs
{
template <class ContainerAllocator>
struct explorer_vice_wheel_
{
  typedef explorer_vice_wheel_<ContainerAllocator> Type;

  explorer_vice_wheel_()
    : front_left_wheel_angular(0.0)
    , front_right_wheel_angular(0.0)
    , back_left_wheel_angular(0.0)
    , back_right_wheel_angular(0.0)  {
    }
  explorer_vice_wheel_(const ContainerAllocator& _alloc)
    : front_left_wheel_angular(0.0)
    , front_right_wheel_angular(0.0)
    , back_left_wheel_angular(0.0)
    , back_right_wheel_angular(0.0)  {
  (void)_alloc;
    }



   typedef double _front_left_wheel_angular_type;
  _front_left_wheel_angular_type front_left_wheel_angular;

   typedef double _front_right_wheel_angular_type;
  _front_right_wheel_angular_type front_right_wheel_angular;

   typedef double _back_left_wheel_angular_type;
  _back_left_wheel_angular_type back_left_wheel_angular;

   typedef double _back_right_wheel_angular_type;
  _back_right_wheel_angular_type back_right_wheel_angular;




  typedef boost::shared_ptr< ::explorer_msgs::explorer_vice_wheel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::explorer_msgs::explorer_vice_wheel_<ContainerAllocator> const> ConstPtr;

}; // struct explorer_vice_wheel_

typedef ::explorer_msgs::explorer_vice_wheel_<std::allocator<void> > explorer_vice_wheel;

typedef boost::shared_ptr< ::explorer_msgs::explorer_vice_wheel > explorer_vice_wheelPtr;
typedef boost::shared_ptr< ::explorer_msgs::explorer_vice_wheel const> explorer_vice_wheelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::explorer_msgs::explorer_vice_wheel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::explorer_msgs::explorer_vice_wheel_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace explorer_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'explorer_msgs': ['/home/hdh/catkin_ws/src/explorer/explorer_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::explorer_msgs::explorer_vice_wheel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::explorer_msgs::explorer_vice_wheel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::explorer_msgs::explorer_vice_wheel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::explorer_msgs::explorer_vice_wheel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::explorer_msgs::explorer_vice_wheel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::explorer_msgs::explorer_vice_wheel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::explorer_msgs::explorer_vice_wheel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4eecacbcd42b965de650e96f6aaff530";
  }

  static const char* value(const ::explorer_msgs::explorer_vice_wheel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4eecacbcd42b965dULL;
  static const uint64_t static_value2 = 0xe650e96f6aaff530ULL;
};

template<class ContainerAllocator>
struct DataType< ::explorer_msgs::explorer_vice_wheel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "explorer_msgs/explorer_vice_wheel";
  }

  static const char* value(const ::explorer_msgs::explorer_vice_wheel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::explorer_msgs::explorer_vice_wheel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 front_left_wheel_angular\n\
float64 front_right_wheel_angular\n\
float64 back_left_wheel_angular\n\
float64 back_right_wheel_angular\n\
";
  }

  static const char* value(const ::explorer_msgs::explorer_vice_wheel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::explorer_msgs::explorer_vice_wheel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.front_left_wheel_angular);
      stream.next(m.front_right_wheel_angular);
      stream.next(m.back_left_wheel_angular);
      stream.next(m.back_right_wheel_angular);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct explorer_vice_wheel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::explorer_msgs::explorer_vice_wheel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::explorer_msgs::explorer_vice_wheel_<ContainerAllocator>& v)
  {
    s << indent << "front_left_wheel_angular: ";
    Printer<double>::stream(s, indent + "  ", v.front_left_wheel_angular);
    s << indent << "front_right_wheel_angular: ";
    Printer<double>::stream(s, indent + "  ", v.front_right_wheel_angular);
    s << indent << "back_left_wheel_angular: ";
    Printer<double>::stream(s, indent + "  ", v.back_left_wheel_angular);
    s << indent << "back_right_wheel_angular: ";
    Printer<double>::stream(s, indent + "  ", v.back_right_wheel_angular);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXPLORER_MSGS_MESSAGE_EXPLORER_VICE_WHEEL_H
