// Generated by gencpp from file explorer_msgs/explorer_agreement.msg
// DO NOT EDIT!


#ifndef EXPLORER_MSGS_MESSAGE_EXPLORER_AGREEMENT_H
#define EXPLORER_MSGS_MESSAGE_EXPLORER_AGREEMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace explorer_msgs
{
template <class ContainerAllocator>
struct explorer_agreement_
{
  typedef explorer_agreement_<ContainerAllocator> Type;

  explorer_agreement_()
    : msg()  {
    }
  explorer_agreement_(const ContainerAllocator& _alloc)
    : msg(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _msg_type;
  _msg_type msg;




  typedef boost::shared_ptr< ::explorer_msgs::explorer_agreement_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::explorer_msgs::explorer_agreement_<ContainerAllocator> const> ConstPtr;

}; // struct explorer_agreement_

typedef ::explorer_msgs::explorer_agreement_<std::allocator<void> > explorer_agreement;

typedef boost::shared_ptr< ::explorer_msgs::explorer_agreement > explorer_agreementPtr;
typedef boost::shared_ptr< ::explorer_msgs::explorer_agreement const> explorer_agreementConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::explorer_msgs::explorer_agreement_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::explorer_msgs::explorer_agreement_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace explorer_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'explorer_msgs': ['/home/hdh/catkin_ws/src/explorer/explorer_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::explorer_msgs::explorer_agreement_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::explorer_msgs::explorer_agreement_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::explorer_msgs::explorer_agreement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::explorer_msgs::explorer_agreement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::explorer_msgs::explorer_agreement_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::explorer_msgs::explorer_agreement_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::explorer_msgs::explorer_agreement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "83d5736a625d65b9db41b52fcc4c43da";
  }

  static const char* value(const ::explorer_msgs::explorer_agreement_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x83d5736a625d65b9ULL;
  static const uint64_t static_value2 = 0xdb41b52fcc4c43daULL;
};

template<class ContainerAllocator>
struct DataType< ::explorer_msgs::explorer_agreement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "explorer_msgs/explorer_agreement";
  }

  static const char* value(const ::explorer_msgs::explorer_agreement_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::explorer_msgs::explorer_agreement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[] msg\n\
";
  }

  static const char* value(const ::explorer_msgs::explorer_agreement_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::explorer_msgs::explorer_agreement_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct explorer_agreement_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::explorer_msgs::explorer_agreement_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::explorer_msgs::explorer_agreement_<ContainerAllocator>& v)
  {
    s << indent << "msg[]" << std::endl;
    for (size_t i = 0; i < v.msg.size(); ++i)
    {
      s << indent << "  msg[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.msg[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXPLORER_MSGS_MESSAGE_EXPLORER_AGREEMENT_H
