// Generated by gencpp from file explorer_msgs/explorer_moveit_paw.msg
// DO NOT EDIT!


#ifndef EXPLORER_MSGS_MESSAGE_EXPLORER_MOVEIT_PAW_H
#define EXPLORER_MSGS_MESSAGE_EXPLORER_MOVEIT_PAW_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace explorer_msgs
{
template <class ContainerAllocator>
struct explorer_moveit_paw_
{
  typedef explorer_moveit_paw_<ContainerAllocator> Type;

  explorer_moveit_paw_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , rotate(0.0)
    , up_down(0.0)
    , left_right(0.0)  {
    }
  explorer_moveit_paw_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , rotate(0.0)
    , up_down(0.0)
    , left_right(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _rotate_type;
  _rotate_type rotate;

   typedef double _up_down_type;
  _up_down_type up_down;

   typedef double _left_right_type;
  _left_right_type left_right;




  typedef boost::shared_ptr< ::explorer_msgs::explorer_moveit_paw_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::explorer_msgs::explorer_moveit_paw_<ContainerAllocator> const> ConstPtr;

}; // struct explorer_moveit_paw_

typedef ::explorer_msgs::explorer_moveit_paw_<std::allocator<void> > explorer_moveit_paw;

typedef boost::shared_ptr< ::explorer_msgs::explorer_moveit_paw > explorer_moveit_pawPtr;
typedef boost::shared_ptr< ::explorer_msgs::explorer_moveit_paw const> explorer_moveit_pawConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::explorer_msgs::explorer_moveit_paw_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::explorer_msgs::explorer_moveit_paw_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace explorer_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'explorer_msgs': ['/home/hdh/catkin_ws/src/explorer/explorer_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::explorer_msgs::explorer_moveit_paw_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::explorer_msgs::explorer_moveit_paw_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::explorer_msgs::explorer_moveit_paw_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::explorer_msgs::explorer_moveit_paw_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::explorer_msgs::explorer_moveit_paw_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::explorer_msgs::explorer_moveit_paw_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::explorer_msgs::explorer_moveit_paw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c901c18a2c51b840fc550ed8177da175";
  }

  static const char* value(const ::explorer_msgs::explorer_moveit_paw_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc901c18a2c51b840ULL;
  static const uint64_t static_value2 = 0xfc550ed8177da175ULL;
};

template<class ContainerAllocator>
struct DataType< ::explorer_msgs::explorer_moveit_paw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "explorer_msgs/explorer_moveit_paw";
  }

  static const char* value(const ::explorer_msgs::explorer_moveit_paw_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::explorer_msgs::explorer_moveit_paw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
float64 z\n\
float64 rotate\n\
float64 up_down\n\
float64 left_right\n\
";
  }

  static const char* value(const ::explorer_msgs::explorer_moveit_paw_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::explorer_msgs::explorer_moveit_paw_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.rotate);
      stream.next(m.up_down);
      stream.next(m.left_right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct explorer_moveit_paw_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::explorer_msgs::explorer_moveit_paw_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::explorer_msgs::explorer_moveit_paw_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "rotate: ";
    Printer<double>::stream(s, indent + "  ", v.rotate);
    s << indent << "up_down: ";
    Printer<double>::stream(s, indent + "  ", v.up_down);
    s << indent << "left_right: ";
    Printer<double>::stream(s, indent + "  ", v.left_right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXPLORER_MSGS_MESSAGE_EXPLORER_MOVEIT_PAW_H
