// Generated by gencpp from file explorer_msgs/explorer_message.msg
// DO NOT EDIT!


#ifndef EXPLORER_MSGS_MESSAGE_EXPLORER_MESSAGE_H
#define EXPLORER_MSGS_MESSAGE_EXPLORER_MESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace explorer_msgs
{
template <class ContainerAllocator>
struct explorer_message_
{
  typedef explorer_message_<ContainerAllocator> Type;

  explorer_message_()
    : high_level_id(0)
    , low_level_id(0)
    , data()  {
    }
  explorer_message_(const ContainerAllocator& _alloc)
    : high_level_id(0)
    , low_level_id(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _high_level_id_type;
  _high_level_id_type high_level_id;

   typedef int64_t _low_level_id_type;
  _low_level_id_type low_level_id;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::explorer_msgs::explorer_message_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::explorer_msgs::explorer_message_<ContainerAllocator> const> ConstPtr;

}; // struct explorer_message_

typedef ::explorer_msgs::explorer_message_<std::allocator<void> > explorer_message;

typedef boost::shared_ptr< ::explorer_msgs::explorer_message > explorer_messagePtr;
typedef boost::shared_ptr< ::explorer_msgs::explorer_message const> explorer_messageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::explorer_msgs::explorer_message_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::explorer_msgs::explorer_message_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace explorer_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'explorer_msgs': ['/home/hdh/catkin_ws/src/explorer/explorer_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::explorer_msgs::explorer_message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::explorer_msgs::explorer_message_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::explorer_msgs::explorer_message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::explorer_msgs::explorer_message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::explorer_msgs::explorer_message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::explorer_msgs::explorer_message_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::explorer_msgs::explorer_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "77bc677472442b3014493c9876db2f54";
  }

  static const char* value(const ::explorer_msgs::explorer_message_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x77bc677472442b30ULL;
  static const uint64_t static_value2 = 0x14493c9876db2f54ULL;
};

template<class ContainerAllocator>
struct DataType< ::explorer_msgs::explorer_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "explorer_msgs/explorer_message";
  }

  static const char* value(const ::explorer_msgs::explorer_message_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::explorer_msgs::explorer_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 high_level_id\n\
int64 low_level_id\n\
float64[] data\n\
";
  }

  static const char* value(const ::explorer_msgs::explorer_message_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::explorer_msgs::explorer_message_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.high_level_id);
      stream.next(m.low_level_id);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct explorer_message_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::explorer_msgs::explorer_message_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::explorer_msgs::explorer_message_<ContainerAllocator>& v)
  {
    s << indent << "high_level_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.high_level_id);
    s << indent << "low_level_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.low_level_id);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXPLORER_MSGS_MESSAGE_EXPLORER_MESSAGE_H
