// Generated by gencpp from file explorer_msgs/explorer_moveit_values.msg
// DO NOT EDIT!


#ifndef EXPLORER_MSGS_MESSAGE_EXPLORER_MOVEIT_VALUES_H
#define EXPLORER_MSGS_MESSAGE_EXPLORER_MOVEIT_VALUES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace explorer_msgs
{
template <class ContainerAllocator>
struct explorer_moveit_values_
{
  typedef explorer_moveit_values_<ContainerAllocator> Type;

  explorer_moveit_values_()
    : names()
    , values()  {
    }
  explorer_moveit_values_(const ContainerAllocator& _alloc)
    : names(_alloc)
    , values(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int64_t, typename ContainerAllocator::template rebind<int64_t>::other >  _names_type;
  _names_type names;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _values_type;
  _values_type values;




  typedef boost::shared_ptr< ::explorer_msgs::explorer_moveit_values_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::explorer_msgs::explorer_moveit_values_<ContainerAllocator> const> ConstPtr;

}; // struct explorer_moveit_values_

typedef ::explorer_msgs::explorer_moveit_values_<std::allocator<void> > explorer_moveit_values;

typedef boost::shared_ptr< ::explorer_msgs::explorer_moveit_values > explorer_moveit_valuesPtr;
typedef boost::shared_ptr< ::explorer_msgs::explorer_moveit_values const> explorer_moveit_valuesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::explorer_msgs::explorer_moveit_values_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::explorer_msgs::explorer_moveit_values_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace explorer_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'explorer_msgs': ['/home/hdh/catkin_ws/src/explorer/explorer_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::explorer_msgs::explorer_moveit_values_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::explorer_msgs::explorer_moveit_values_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::explorer_msgs::explorer_moveit_values_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::explorer_msgs::explorer_moveit_values_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::explorer_msgs::explorer_moveit_values_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::explorer_msgs::explorer_moveit_values_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::explorer_msgs::explorer_moveit_values_<ContainerAllocator> >
{
  static const char* value()
  {
    return "84f9a3f8e9c29a8f79c74eb12e14fcec";
  }

  static const char* value(const ::explorer_msgs::explorer_moveit_values_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x84f9a3f8e9c29a8fULL;
  static const uint64_t static_value2 = 0x79c74eb12e14fcecULL;
};

template<class ContainerAllocator>
struct DataType< ::explorer_msgs::explorer_moveit_values_<ContainerAllocator> >
{
  static const char* value()
  {
    return "explorer_msgs/explorer_moveit_values";
  }

  static const char* value(const ::explorer_msgs::explorer_moveit_values_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::explorer_msgs::explorer_moveit_values_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64[] names\n\
float64[] values\n\
\n\
";
  }

  static const char* value(const ::explorer_msgs::explorer_moveit_values_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::explorer_msgs::explorer_moveit_values_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.names);
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct explorer_moveit_values_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::explorer_msgs::explorer_moveit_values_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::explorer_msgs::explorer_moveit_values_<ContainerAllocator>& v)
  {
    s << indent << "names[]" << std::endl;
    for (size_t i = 0; i < v.names.size(); ++i)
    {
      s << indent << "  names[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.names[i]);
    }
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXPLORER_MSGS_MESSAGE_EXPLORER_MOVEIT_VALUES_H
