// Generated by gencpp from file explorer_msgs/light_control.msg
// DO NOT EDIT!


#ifndef EXPLORER_MSGS_MESSAGE_LIGHT_CONTROL_H
#define EXPLORER_MSGS_MESSAGE_LIGHT_CONTROL_H

#include <ros/service_traits.h>


#include <explorer_msgs/light_controlRequest.h>
#include <explorer_msgs/light_controlResponse.h>


namespace explorer_msgs
{

struct light_control
{

typedef light_controlRequest Request;
typedef light_controlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct light_control
} // namespace explorer_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::explorer_msgs::light_control > {
  static const char* value()
  {
    return "3026467b703261111d596d8ddecb028c";
  }

  static const char* value(const ::explorer_msgs::light_control&) { return value(); }
};

template<>
struct DataType< ::explorer_msgs::light_control > {
  static const char* value()
  {
    return "explorer_msgs/light_control";
  }

  static const char* value(const ::explorer_msgs::light_control&) { return value(); }
};


// service_traits::MD5Sum< ::explorer_msgs::light_controlRequest> should match 
// service_traits::MD5Sum< ::explorer_msgs::light_control > 
template<>
struct MD5Sum< ::explorer_msgs::light_controlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::explorer_msgs::light_control >::value();
  }
  static const char* value(const ::explorer_msgs::light_controlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::explorer_msgs::light_controlRequest> should match 
// service_traits::DataType< ::explorer_msgs::light_control > 
template<>
struct DataType< ::explorer_msgs::light_controlRequest>
{
  static const char* value()
  {
    return DataType< ::explorer_msgs::light_control >::value();
  }
  static const char* value(const ::explorer_msgs::light_controlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::explorer_msgs::light_controlResponse> should match 
// service_traits::MD5Sum< ::explorer_msgs::light_control > 
template<>
struct MD5Sum< ::explorer_msgs::light_controlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::explorer_msgs::light_control >::value();
  }
  static const char* value(const ::explorer_msgs::light_controlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::explorer_msgs::light_controlResponse> should match 
// service_traits::DataType< ::explorer_msgs::light_control > 
template<>
struct DataType< ::explorer_msgs::light_controlResponse>
{
  static const char* value()
  {
    return DataType< ::explorer_msgs::light_control >::value();
  }
  static const char* value(const ::explorer_msgs::light_controlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXPLORER_MSGS_MESSAGE_LIGHT_CONTROL_H
