// Generated by gencpp from file explorer_app_msgs/app_arm_info.msg
// DO NOT EDIT!


#ifndef EXPLORER_APP_MSGS_MESSAGE_APP_ARM_INFO_H
#define EXPLORER_APP_MSGS_MESSAGE_APP_ARM_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace explorer_app_msgs
{
template <class ContainerAllocator>
struct app_arm_info_
{
  typedef app_arm_info_<ContainerAllocator> Type;

  app_arm_info_()
    : header()
    , id(0)
    , angular(0)  {
    }
  app_arm_info_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , angular(0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _id_type;
  _id_type id;

   typedef int64_t _angular_type;
  _angular_type angular;




  typedef boost::shared_ptr< ::explorer_app_msgs::app_arm_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::explorer_app_msgs::app_arm_info_<ContainerAllocator> const> ConstPtr;

}; // struct app_arm_info_

typedef ::explorer_app_msgs::app_arm_info_<std::allocator<void> > app_arm_info;

typedef boost::shared_ptr< ::explorer_app_msgs::app_arm_info > app_arm_infoPtr;
typedef boost::shared_ptr< ::explorer_app_msgs::app_arm_info const> app_arm_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::explorer_app_msgs::app_arm_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::explorer_app_msgs::app_arm_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace explorer_app_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'explorer_app_msgs': ['/home/exbot/Document/ROS/explorer_test/src/explorer_app_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::explorer_app_msgs::app_arm_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::explorer_app_msgs::app_arm_info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::explorer_app_msgs::app_arm_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::explorer_app_msgs::app_arm_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::explorer_app_msgs::app_arm_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::explorer_app_msgs::app_arm_info_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::explorer_app_msgs::app_arm_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ae256a74247fc7d0e24ec97ebdfb4fcf";
  }

  static const char* value(const ::explorer_app_msgs::app_arm_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xae256a74247fc7d0ULL;
  static const uint64_t static_value2 = 0xe24ec97ebdfb4fcfULL;
};

template<class ContainerAllocator>
struct DataType< ::explorer_app_msgs::app_arm_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "explorer_app_msgs/app_arm_info";
  }

  static const char* value(const ::explorer_app_msgs::app_arm_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::explorer_app_msgs::app_arm_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int64 id\n\
int64 angular\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::explorer_app_msgs::app_arm_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::explorer_app_msgs::app_arm_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.angular);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct app_arm_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::explorer_app_msgs::app_arm_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::explorer_app_msgs::app_arm_info_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
    s << indent << "angular: ";
    Printer<int64_t>::stream(s, indent + "  ", v.angular);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXPLORER_APP_MSGS_MESSAGE_APP_ARM_INFO_H
