# This service is called to ask other nodes for their opinion about a percept

# The percept
PosePercept percept
---
# The response
uint8 response
uint8 UNKNOWN = 0
uint8 DISCARD = 1
uint8 CONFIRM = 2
