controller_list:
  - name: fake_explorer_arm_controller
    joints:
      - arm1_bearing_joint
      - arm2_arm1_joint
      - arm3_arm2_joint
      - pt1_arm_joint
      - pt2_pt1_joint
      - rotate_joint
  - name: fake_explorer_paw_controller
    joints:
      - pt1_arm_joint
      - pt2_pt1_joint
      - rotate_joint