// Generated by gencpp from file explorer_msgs/explorer_low_level_data.msg
// DO NOT EDIT!


#ifndef EXPLORER_MSGS_MESSAGE_EXPLORER_LOW_LEVEL_DATA_H
#define EXPLORER_MSGS_MESSAGE_EXPLORER_LOW_LEVEL_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace explorer_msgs
{
template <class ContainerAllocator>
struct explorer_low_level_data_
{
  typedef explorer_low_level_data_<ContainerAllocator> Type;

  explorer_low_level_data_()
    : low_level_id(0)
    , can_serial_data_1(0.0)
    , can_serial_data_2(0.0)  {
    }
  explorer_low_level_data_(const ContainerAllocator& _alloc)
    : low_level_id(0)
    , can_serial_data_1(0.0)
    , can_serial_data_2(0.0)  {
  (void)_alloc;
    }



   typedef int64_t _low_level_id_type;
  _low_level_id_type low_level_id;

   typedef double _can_serial_data_1_type;
  _can_serial_data_1_type can_serial_data_1;

   typedef double _can_serial_data_2_type;
  _can_serial_data_2_type can_serial_data_2;




  typedef boost::shared_ptr< ::explorer_msgs::explorer_low_level_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::explorer_msgs::explorer_low_level_data_<ContainerAllocator> const> ConstPtr;

}; // struct explorer_low_level_data_

typedef ::explorer_msgs::explorer_low_level_data_<std::allocator<void> > explorer_low_level_data;

typedef boost::shared_ptr< ::explorer_msgs::explorer_low_level_data > explorer_low_level_dataPtr;
typedef boost::shared_ptr< ::explorer_msgs::explorer_low_level_data const> explorer_low_level_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::explorer_msgs::explorer_low_level_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::explorer_msgs::explorer_low_level_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace explorer_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'explorer_msgs': ['/home/hdh/catkin_ws/src/explorer/explorer_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::explorer_msgs::explorer_low_level_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::explorer_msgs::explorer_low_level_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::explorer_msgs::explorer_low_level_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::explorer_msgs::explorer_low_level_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::explorer_msgs::explorer_low_level_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::explorer_msgs::explorer_low_level_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::explorer_msgs::explorer_low_level_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "464c3ddb9b7fad8e12a26ddca6b44988";
  }

  static const char* value(const ::explorer_msgs::explorer_low_level_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x464c3ddb9b7fad8eULL;
  static const uint64_t static_value2 = 0x12a26ddca6b44988ULL;
};

template<class ContainerAllocator>
struct DataType< ::explorer_msgs::explorer_low_level_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "explorer_msgs/explorer_low_level_data";
  }

  static const char* value(const ::explorer_msgs::explorer_low_level_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::explorer_msgs::explorer_low_level_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 low_level_id\n\
float64 can_serial_data_1\n\
float64 can_serial_data_2\n\
";
  }

  static const char* value(const ::explorer_msgs::explorer_low_level_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::explorer_msgs::explorer_low_level_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.low_level_id);
      stream.next(m.can_serial_data_1);
      stream.next(m.can_serial_data_2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct explorer_low_level_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::explorer_msgs::explorer_low_level_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::explorer_msgs::explorer_low_level_data_<ContainerAllocator>& v)
  {
    s << indent << "low_level_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.low_level_id);
    s << indent << "can_serial_data_1: ";
    Printer<double>::stream(s, indent + "  ", v.can_serial_data_1);
    s << indent << "can_serial_data_2: ";
    Printer<double>::stream(s, indent + "  ", v.can_serial_data_2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXPLORER_MSGS_MESSAGE_EXPLORER_LOW_LEVEL_DATA_H
